/*
 * What the dongle plays - one square-wave voice, the way the arcade's three
 * sounded.  A tone is a frequency, a glide from one to another, or a rest;
 * a tune is a list of them, and the priority decides which one wins when two
 * want the voice at once.
 *
 * Generated by tools/tunes.py; edit that, not this.
 *
 * SPDX-License-Identifier: MIT
 */

#pragma once

#include "pacman_sfx.h"


static const pm_tone pm_tune_intro_tones[] = {
    {494, 494, 120, 50},
    {988, 988, 120, 50},
    {740, 740, 120, 50},
    {622, 622, 120, 50},
    {988, 988, 60, 50},
    {740, 740, 60, 50},
    {622, 622, 240, 50},
    {523, 523, 120, 50},
    {1047, 1047, 120, 50},
    {784, 784, 120, 50},
    {659, 659, 120, 50},
    {1047, 1047, 60, 50},
    {784, 784, 60, 50},
    {659, 659, 240, 50},
};

static const pm_tone pm_tune_munch_a_tones[] = {
    {1046, 440, 70, 40},
};

static const pm_tone pm_tune_munch_b_tones[] = {
    {440, 1046, 70, 40},
};

static const pm_tone pm_tune_power_tones[] = {
    {392, 784, 90, 25},
    {784, 1568, 90, 25},
};

static const pm_tone pm_tune_siren_tones[] = {
    {330, 660, 160, 25},
    {660, 330, 160, 25},
};

static const pm_tone pm_tune_ghost_tones[] = {
    {220, 1760, 380, 25},
};

static const pm_tone pm_tune_death_tones[] = {
    {620, 200, 300, 50},
    {0, 0, 40, 0},
    {580, 180, 300, 50},
    {0, 0, 40, 0},
    {540, 160, 300, 50},
    {0, 0, 40, 0},
    {500, 120, 360, 50},
};

static const pm_tone pm_tune_clear_tones[] = {
    {523, 523, 100, 50},
    {659, 659, 100, 50},
    {784, 784, 100, 50},
    {1047, 1047, 100, 50},
    {1319, 1319, 100, 50},
    {1568, 1568, 300, 50},
};

static const pm_tune PM_TUNES[PM_TUNE_COUNT] = {
    [PM_TUNE_INTRO] = {pm_tune_intro_tones, 14, false, 3},
    [PM_TUNE_MUNCH_A] = {pm_tune_munch_a_tones, 1, false, 1},
    [PM_TUNE_MUNCH_B] = {pm_tune_munch_b_tones, 1, false, 1},
    [PM_TUNE_POWER] = {pm_tune_power_tones, 2, false, 2},
    [PM_TUNE_SIREN] = {pm_tune_siren_tones, 2, true, 0},
    [PM_TUNE_GHOST] = {pm_tune_ghost_tones, 1, false, 2},
    [PM_TUNE_DEATH] = {pm_tune_death_tones, 7, false, 4},
    [PM_TUNE_CLEAR] = {pm_tune_clear_tones, 6, false, 3},
};
