#!/usr/bin/env python3
"""Turn tools/splash_art.png into the header the image splash draws from.

    python3 tools/splash_image.py > boards/shields/pacman_adapter/widgets/splash_image.h

The art is a 240x240 picture of at most eight flat colours, which is what lets
it be a palette and a run length rather than 115KB of pixels: every byte here
is one run - three bits of palette index, five of length - and runs never cross
a row, so the decoder can hand each row to the panel as it finishes one and
never needs a frame buffer.  Eight colours of the poster come to about 8KB.

Editing the picture means running this again; hand-editing the header loses it.
"""
import struct
import sys
import zlib

MAX_COLORS = 8
MAX_RUN = 32


def read_png(path):
    """Just enough PNG for the art: 8-bit truecolour or palette, uninterlaced."""
    data = open(path, 'rb').read()
    if data[:8] != b'\x89PNG\r\n\x1a\n':
        raise SystemExit('%s: not a PNG' % path)
    pos, idat, plte, hdr = 8, b'', None, None
    while pos < len(data):
        (length,) = struct.unpack('>I', data[pos:pos + 4])
        tag = data[pos + 4:pos + 8]
        body = data[pos + 8:pos + 8 + length]
        if tag == b'IHDR':
            hdr = struct.unpack('>IIBBBBB', body)
        elif tag == b'PLTE':
            plte = body
        elif tag == b'IDAT':
            idat += body
        elif tag == b'IEND':
            break
        pos += 12 + length

    w, h, depth, color, _, _, interlace = hdr
    if depth != 8 or interlace:
        raise SystemExit('%s: need an 8-bit uninterlaced PNG' % path)
    channels = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}[color]
    raw = zlib.decompress(idat)
    stride = w * channels

    out, prev = [], bytearray(stride)
    pos = 0
    for _ in range(h):
        filt = raw[pos]
        line = bytearray(raw[pos + 1:pos + 1 + stride])
        pos += 1 + stride
        for i in range(stride):
            a = line[i - channels] if i >= channels else 0
            b = prev[i]
            c = prev[i - channels] if i >= channels else 0
            if filt == 1:
                line[i] = (line[i] + a) & 0xFF
            elif filt == 2:
                line[i] = (line[i] + b) & 0xFF
            elif filt == 3:
                line[i] = (line[i] + (a + b) // 2) & 0xFF
            elif filt == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pr = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                line[i] = (line[i] + pr) & 0xFF
        prev = line
        if color == 3:
            out.append([tuple(plte[3 * v:3 * v + 3]) for v in line])
        else:
            out.append([tuple(line[i:i + 3]) for i in range(0, stride, channels)])
    return w, h, out


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else 'tools/splash_art.png'
    w, h, rows = read_png(path)

    # the palette in the order the picture uses it, commonest first, so index 0
    # is the ground and a glance down the header says what the art is made of
    counts = {}
    for row in rows:
        for px in row:
            counts[px] = counts.get(px, 0) + 1
    palette = sorted(counts, key=lambda c: -counts[c])
    if len(palette) > MAX_COLORS:
        raise SystemExit('%s has %d colours; the format holds %d - quantize it first'
                         % (path, len(palette), MAX_COLORS))
    index = {c: i for i, c in enumerate(palette)}

    runs = []
    for row in rows:
        prev, n = index[row[0]], 1
        for px in row[1:]:
            v = index[px]
            if v == prev and n < MAX_RUN:
                n += 1
            else:
                runs.append((prev, n))
                prev, n = v, 1
        runs.append((prev, n))

    print('/*')
    print(' * Pac-Man dongle - the picture the image splash draws.')
    print(' *')
    print(' * Generated by tools/splash_image.py from %s; edit the picture and' % path)
    print(' * run it again rather than this file.  One byte per run: the palette index')
    print(' * in the top three bits, the run length less one in the bottom five.  Runs')
    print(' * stop at the end of a row, so a decoder that has counted %d pixels is' % w)
    print(' * holding a finished row and never needs more than that.')
    print(' *')
    print(' * SPDX-License-Identifier: MIT')
    print(' */')
    print()
    print('#pragma once')
    print()
    print('#include <stdint.h>')
    print()
    print('#define SPLASH_IMAGE_WIDTH %d' % w)
    print('#define SPLASH_IMAGE_HEIGHT %d' % h)
    print('#define SPLASH_IMAGE_COLORS %d' % len(palette))
    print()
    print('/* rrggbb, turned into the panel\'s 565 where it is drawn */')
    print('static const uint32_t splash_image_palette[SPLASH_IMAGE_COLORS] = {')
    for c in palette:
        print('    0x%02x%02x%02x, /* %d pixels */' % (c[0], c[1], c[2], counts[c]))
    print('};')
    print()
    print('static const uint8_t splash_image_runs[] = {')
    line = '   '
    for (v, n) in runs:
        line += ' 0x%02x,' % ((v << 5) | (n - 1))
        if len(line) > 92:
            print(line)
            line = '   '
    if line.strip():
        print(line)
    print('};')
    print()
    print('/* %d runs over %d rows */' % (len(runs), h))


if __name__ == '__main__':
    main()
