"""
Generates widgets/pacman_art.h - the splash sprites.

Pac-Man is a disc with a wedge cut out of it; the ghost is a dome on three
scalloped feet with eyes looking the way it runs.  Both come out as plain
integer arrays: 1 is the body, and the ghost also uses 2 for the whites of
its eyes and 3 for the pupils, which is what render_bitmap_multicolor() wants.

    python3 tools/sprites.py > boards/shields/pacman_adapter/widgets/pacman_art.h
"""

import math


def pac(size=40, mouth_deg=35.0):
    r, c = size / 2.0, (size - 1) / 2.0
    out = []
    for y in range(size):
        row = []
        for x in range(size):
            dx, dy = x - c, y - c
            on = dx * dx + dy * dy <= (r - 0.5) ** 2
            if on and abs(math.degrees(math.atan2(dy, dx))) <= mouth_deg:
                on = False
            row.append(1 if on else 0)
        out.append(row)
    return out


def ghost(w=36, h=36):
    rows = [[0] * w for _ in range(h)]
    r, cx = w / 2.0, (w - 1) / 2.0
    dome_cy, foot_r = r - 0.5, w / 6.0
    feet_cy = h - 1 - foot_r
    for y in range(h):
        for x in range(w):
            dx = x - cx
            if y <= dome_cy:
                on = dx * dx + (y - dome_cy) ** 2 <= (r - 0.5) ** 2
            elif y <= feet_cy:
                on = abs(dx) <= r - 0.5
            else:
                on = any(
                    (x - ((k + 0.5) * (w / 3.0) - 0.5)) ** 2 + (y - feet_cy) ** 2 <= (foot_r - 0.5) ** 2
                    for k in range(3)
                )
            rows[y][x] = 1 if on else 0

    eye_r, pup_r = w / 7.0, w / 14.0
    for ex in (cx - w / 5.5, cx + w / 5.5):
        ey = r - 1.5
        for y in range(h):
            for x in range(w):
                if (x - ex) ** 2 + (y - ey) ** 2 <= eye_r ** 2 and rows[y][x]:
                    rows[y][x] = 2
        for y in range(h):
            for x in range(w):
                if (x - (ex - eye_r / 2)) ** 2 + (y - ey) ** 2 <= pup_r ** 2 and rows[y][x] == 2:
                    rows[y][x] = 3
    return rows


def emit(name, rows):
    h, w = len(rows), len(rows[0])
    out = f"const static uint16_t {name}_width = {w};\n"
    out += f"const static uint16_t {name}_height = {h};\n"
    out += f"static const uint16_t {name}[{h}][{w}] = {{\n"
    for row in rows:
        out += "    {" + ", ".join(str(v) for v in row) + "},\n"
    return out + "};\n"


HEADER = """/*
 * Splash artwork: the two faces of the game, drawn once as bitmaps so the
 * splash can blit them a row at a time the way the rest of the UI does.
 *
 * Pac-Man is a disc with a wedge cut out of it, facing the ghost he is about
 * to run into.  The ghost's pixels are colour indices rather than a mask - 1
 * the body, 2 the whites of the eyes, 3 the pupils - so one call to
 * render_bitmap_multicolor() draws it.
 *
 * Generated by tools/sprites.py; edit that, not this.
 *
 * SPDX-License-Identifier: MIT
 */

#pragma once

#include <zephyr/kernel.h>

"""

if __name__ == "__main__":
    print(HEADER + emit("splash_pac", pac()) + "\n" + emit("splash_ghost", ghost()), end="")
