"""
Generates widgets/game/pacman_tunes.h - the sine table and what the dongle plays.

The speaker is a DAC and an amplifier, not a buzzer, so these are scores rather
than beeps: notes with a pitch, a length and an instrument, several of them
sounding at once.  Written here in notation, and turned into the note lists the
synth reads.

    python3 tools/tunes.py > boards/shields/pacman_adapter/widgets/game/pacman_tunes.h
"""

import math

NOTES = {"C": 0, "C#": 1, "D": 2, "D#": 3, "E": 4, "F": 5, "F#": 6,
         "G": 7, "G#": 8, "A": 9, "A#": 10, "B": 11}

BELL, PLUCK, PAD, NOISE = "PM_INST_BELL", "PM_INST_PLUCK", "PM_INST_PAD", "PM_INST_NOISE"
CHIME = "PM_INST_CHIME"


def hz(note):
    """"A4" -> 440.  Octave 4 is the one that starts at middle C."""
    name, octave = note[:-1], int(note[-1])
    midi = 12 * (octave + 1) + NOTES[name]
    return int(round(440.0 * (2.0 ** ((midi - 69) / 12.0))))


def n(at, note, ms, inst=BELL, level=100):
    """one note: when it starts, what pitch, how long the key is held"""
    return (at, hz(note) if note else 0, ms, inst, level)


def chord(at, notes, ms, inst=PAD, level=100, spread=0):
    """several at once, or rolled if spread is given"""
    return [n(at + i * spread, note, ms - i * spread, inst, level)
            for i, note in enumerate(notes)]


# ---------------------------------------------------------------- the tunes
#
# Two sounds, and both are status rather than music: a keyboard arriving, and
# one going away.
#
# They have been wrong twice, in opposite directions.  First they were written
# like the game's tunes were - a rolled arpeggio landing on a bell over a pad
# at 131 and 196 Hz, which a 20 mm speaker is 20 dB down on, so the pad spent
# headroom without reaching the room and the bell rang for 1200 ms after an
# event that took an instant.  Then they were plucks up at 880 and 1319 Hz to
# fix the length, and a pluck is a triangle: odd harmonics at 4 and 6.6 kHz,
# right where the ear is sharpest and a small cone peaks.  Short, and it stung.
#
# What was wrong both times was timbre and attack, not the notes.  So: the
# chime, which is a sine with one quiet octave for body and nothing above it,
# on a fifth in the middle of the speaker's range rather than the top of it.
# It takes 110 ms to reach level, which is slow enough to have no audible
# beginning at all, and the second note comes in while the first is still
# ringing, so the pair swells rather than taps - up for a keyboard that has
# arrived, down for one that has gone.

CONNECT = [n(0, "D5", 420, CHIME, 60), n(200, "A5", 560, CHIME, 60)]
DISCONNECT = [n(0, "A5", 420, CHIME, 56), n(200, "D5", 600, CHIME, 56)]

# name, notes, loops, priority, and how long the tune runs before it is over
# or goes round again (None works it out from the last note and its tail)
TUNES = [
    ("PM_TUNE_CONNECT", CONNECT, False, 1, None),
    # a keyboard dropping is the more useful of the two to hear, so it takes
    # the voice off a connect rather than the other way about
    ("PM_TUNE_DISCONNECT", DISCONNECT, False, 2, None),
]

HEADER = '''/*
 * The sine table the oscillators read, and the scores they play.
 *
 * Generated by tools/tunes.py; edit that, not this.
 *
 * SPDX-License-Identifier: MIT
 */

#pragma once

#include "pacman_sfx.h"

'''


def sine_table():
    values = [int(round(16383 * math.sin(2 * math.pi * i / 256))) for i in range(256)]
    rows = [", ".join(f"{v:6}" for v in values[i:i + 8]) for i in range(0, 256, 8)]
    return "#define PM_SINE_TABLE { \\\n" + ", \\\n".join("    " + r for r in rows) + " \\\n}\n"


def main():
    out = [HEADER, sine_table()]
    for name, notes, *_ in TUNES:
        rows = ",\n".join(f"    {{{at}, {f}, {ms}, {inst}, {lvl}}}"
                          for at, f, ms, inst, lvl in sorted(notes))
        out.append(f"static const pm_note {name.lower()}_notes[] = {{\n{rows},\n}};\n")
    rows = []
    for name, notes, loop, prio, length in TUNES:
        # the tune is over when its last note has finished ringing
        tail = {BELL: 1200, PLUCK: 360, PAD: 700, NOISE: 200, CHIME: 520}
        end = length or max(at + ms + tail[inst] for at, _f, ms, inst, _l in notes)
        rows.append(f"    [{name}] = {{{name.lower()}_notes, {len(notes)}, {end}, "
                    f"{'true' if loop else 'false'}, {prio}}}")
    out.append("static const pm_tune PM_TUNES[PM_TUNE_COUNT] = {\n" + ",\n".join(rows) + ",\n};\n")
    print("\n".join(out), end="")


if __name__ == "__main__":
    main()
