"""
Generates widgets/game/pacman_tunes.h - what the dongle plays.

The arcade's sound hardware was three wavetable voices; this is one square
wave, so the tunes are written for it: a note is a frequency, a glide between
two, or a rest, and a tune is a list of them.  Written here in notation rather
than in Hz so the melodies stay readable.

    python3 tools/tunes.py > boards/shields/pacman_adapter/widgets/game/pacman_tunes.h
"""

NOTES = {"C": 0, "C#": 1, "D": 2, "D#": 3, "E": 4, "F": 5, "F#": 6,
         "G": 7, "G#": 8, "A": 9, "A#": 10, "B": 11}


def hz(note):
    """"A4" -> 440.  Octave 4 is the one that starts at middle C."""
    name, octave = note[:-1], int(note[-1])
    midi = 12 * (octave + 1) + NOTES[name]
    return int(round(440.0 * (2.0 ** ((midi - 69) / 12.0))))


def tone(note, ms, duty=50):
    return (hz(note), hz(note), ms, duty)


def glide(from_hz, to_hz, ms, duty=50):
    return (from_hz, to_hz, ms, duty)


def rest(ms):
    return (0, 0, ms, 0)


# The opening fanfare, first phrase.  Everyone knows this one.
INTRO = [
    tone("B4", 120), tone("B5", 120), tone("F#5", 120), tone("D#5", 120),
    tone("B5", 60), tone("F#5", 60), tone("D#5", 240),
    tone("C5", 120), tone("C6", 120), tone("G5", 120), tone("E5", 120),
    tone("C6", 60), tone("G5", 60), tone("E5", 240),
]

# Eating a pellet: a chirp down, then the next one up, alternating, which is
# what gives the arcade its waka-waka when he is running a corridor.
MUNCH_A = [glide(1046, 440, 70, 40)]
MUNCH_B = [glide(440, 1046, 70, 40)]

# A power pellet, and then the siren that runs while the ghosts are blue
POWER = [glide(392, 784, 90, 25), glide(784, 1568, 90, 25)]
SIREN = [glide(330, 660, 160, 25), glide(660, 330, 160, 25)]

# Catching one of them: a rising swoop.  Losing to one: four falling ones.
GHOST = [glide(220, 1760, 380, 25)]
DEATH = [
    glide(620, 200, 300, 50), rest(40),
    glide(580, 180, 300, 50), rest(40),
    glide(540, 160, 300, 50), rest(40),
    glide(500, 120, 360, 50),
]

# And clearing the maze
CLEAR = [
    tone("C5", 100), tone("E5", 100), tone("G5", 100),
    tone("C6", 100), tone("E6", 100), tone("G6", 300),
]

TUNES = [
    ("PM_TUNE_INTRO", INTRO, False, 3),
    ("PM_TUNE_MUNCH_A", MUNCH_A, False, 1),
    ("PM_TUNE_MUNCH_B", MUNCH_B, False, 1),
    ("PM_TUNE_POWER", POWER, False, 2),
    ("PM_TUNE_SIREN", SIREN, True, 0),
    ("PM_TUNE_GHOST", GHOST, False, 2),
    ("PM_TUNE_DEATH", DEATH, False, 4),
    ("PM_TUNE_CLEAR", CLEAR, False, 3),
]

HEADER = '''/*
 * What the dongle plays - one square-wave voice, the way the arcade's three
 * sounded.  A tone is a frequency, a glide from one to another, or a rest;
 * a tune is a list of them, and the priority decides which one wins when two
 * want the voice at once.
 *
 * Generated by tools/tunes.py; edit that, not this.
 *
 * SPDX-License-Identifier: MIT
 */

#pragma once

#include "pacman_sfx.h"

'''


def main():
    out = [HEADER]
    for name, tones, _loop, _prio in TUNES:
        rows = ",\n".join(
            f"    {{{f}, {t}, {ms}, {duty}}}" for f, t, ms, duty in tones)
        out.append(f"static const pm_tone {name.lower()}_tones[] = {{\n{rows},\n}};\n")
    rows = []
    for name, tones, loop, prio in TUNES:
        rows.append(f"    [{name}] = {{{name.lower()}_tones, {len(tones)}, "
                    f"{'true' if loop else 'false'}, {prio}}}")
    out.append("static const pm_tune PM_TUNES[PM_TUNE_COUNT] = {\n" + ",\n".join(rows) + ",\n};\n")
    print("\n".join(out), end="")


if __name__ == "__main__":
    main()
